name: deploy to github pages

on: 
   push:
      branches:
         -master
jobs:
   build:
      runs-on: ubuntu-latest

      stragegy: 
         matrix: 
            node-version:[16.x]

      steps:
         -  name: Checkout
            uses: actions/checkout@v1

         -  name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}

         -  name: Install and Build
            uses: npm install and npm run deploy
            with: 
               branch: gh-pages # The branch the action should deploy to.


