name: deploy to github pages

on: 
   push:
      branches:
         -master
jobs:
   build:
      runs-on: ubuntu-latest

      stragegy: 
         matrix: 
            node-version:[16.x]

      steps:
         -  name: Checkout
            uses: actions/checkout@v1

         -  name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}

         -  name: Install 
            uses: npm install 

         -  name: Deploy
            uses: npm run deploy


