name: deploy to github pages

on: 
   push:
      branches:
         -master
jobs:
   build:
      runs-on: ubuntu-latest

      stragegy: 
         matrix: 
            node-version:[8.x, 10.x, 12.x]

      steps:
         -  name: Checkout
            uses: actions/checkout@v1

         -  name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}



         -  name: Echo
            run: Echo 'teste final'



