name: mvurban - Deploy React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # We will deploy with only one version of node  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 
         uses: actions/checkout@v1  

      - name: Install and build
         run: npm install && npm run build

      -name: deploy
         uses: mvurban/React-Treinos
         with: 
            branch: gh-pages
            folder:build
         
